POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "admin@fastfeet.com",
  "password": "123456"
}

> {%
client.global.set("user", response.body.user);
client.global.set("auth_token", response.body.token);
%}

###
GET http://localhost:3333/sessions
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3333/delivery
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3333/delivery/1
Authorization: Bearer {{auth_token}}

###
POST http://localhost:3334/problems
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "delivery_id": 1,
  "description": "A caixa chegou sem lacre."
}

###
GET http://localhost:3334/problems
Authorization: Bearer {{auth_token}}
