###
POST http://localhost:3334/problems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2NzMyMDg4LCJleHAiOjE2MTczMzY4ODh9.gdZFMX7diPkC92kCn9ChlpXALhreU9qqYX1VFuhCVAM
Content-Type: application/json

{
  "delivery_id": 3,
  "description": "Quebrado."
}

###
GET http://localhost:3334/problems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2NzMyMDg4LCJleHAiOjE2MTczMzY4ODh9.gdZFMX7diPkC92kCn9ChlpXALhreU9qqYX1VFuhCVAM
